analyze: don't introduce useless variable
this also solves the following error on python3:

 AttributeError: 'dict_keys' object has no attribute 'sort'