test/gen_testdata: Fix for ZODB4
This fixes 0b6f99da (test/gen_testdata: Fix for ZODB5 > 5.5.1 + preserve
database compatibility with ZODB3/py2) which broke that program on ZODB4
because there is no TransactionMetaData:

    (neo) (z4-dev) (g.env) kirr@deca:~/src/neo/src/lab.nexedi.com/kirr/neo/go/zodb/btree$ go generate
    Traceback (most recent call last):
      File "./testdata/gen-testdata", line 26, in <module>
        from zodbtools.test.gen_testdata import run_with_zodb4py2_compat
      File "/home/kirr/src/wendelin/z/zodbtools/zodbtools/test/gen_testdata.py", line 42, in <module>
        from ZODB.Connection import TransactionMetaData
    ImportError: cannot import name TransactionMetaData
    btree_test.go:22: running "./testdata/gen-testdata": exit status 1

-> Fix it, similarly to how treegen.py handles this situation in WCFS:

https://lab.nexedi.com/kirr/wendelin.core/commit/4300d88a
https://lab.nexedi.com/kirr/wendelin.core/blob/57be0126/wcfs/internal/xbtree/xbtreetest/treegen.py